"""Prompt templates."""

from .templates import (
    BINARY_PROMPT_TEMPLATE,
    NUMERIC_PROMPT_TEMPLATE,
    MULTIPLE_CHOICE_PROMPT_TEMPLATE,
    RESEARCH_SYSTEM_PROMPT,
)

__all__ = [
    "BINARY_PROMPT_TEMPLATE",
    "NUMERIC_PROMPT_TEMPLATE",
    "MULTIPLE_CHOICE_PROMPT_TEMPLATE",
    "RESEARCH_SYSTEM_PROMPT",
]
